version: '3.7'
services:
  mariadb:
    container_name: s4t_iotronic_db
    restart: unless-stopped
    image: smartmeio/mariadb:focal
    environment:
      - MYSQL_ROOT_PASSWORD="smartme"
      - MARIADB_ROOT_PASSWORD="smartme"
    volumes:
      - 's4t_iotronic_db_data:/var/lib/mysql'
      - 's4t_iotronic_db_config:/etc/mysql'
    ports:
      - '3306:3306'
    networks:
      - 'default'

  rabbitmq:
    container_name: s4t_rabbitmq
    restart: unless-stopped
    image: smartmeio/s4t_rabbitmq:3.9.8
    environment:
      - RABBIT_PASS="smartme"
    ports:
      - '5672:5672'
    networks:
      - 'default'

  keystone:
    container_name: s4t_keystone
    restart: unless-stopped
    image: smartmeio/s4t_keystone:stein
    environment:
      - OS_PROJECT_DOMAIN_NAME=Default
      - OS_USER_DOMAIN_NAME=Default
      - OS_PROJECT_NAME=admin
      - OS_USERNAME=admin
      - OS_PASSWORD=smartme
      - OS_AUTH_URL=https://demo-controller.smartme.io:5000/v3
      - OS_IDENTITY_API_VERSION=3
      - OS_IMAGE_API_VERSION=2
      - HOST="demo-controller.smartme.io"
      - ADMIN_PASS="smartme"
      - URL="https://demo-controller.smartme.io:5000/v3"
    volumes:
      - s4t_keystone_config:/etc/keystone/
      - s4t_keystone_data:/var/lib/keystone/
      - /var/log/keystone:/var/log/keystone
      - /var/log/keystone-api:/var/log/apache2
    depends_on:
      - mariadb
      - rabbitmq
    ports:
      - '5001:5000'
    networks:
      - 'default'

  conductor:
    container_name: s4t_iotronic_conductor
    restart: unless-stopped
    image: smartmeio/s4t_iotronic_conductor:latest
    environment:
      - OS_PROJECT_DOMAIN_NAME=Default
      - OS_USER_DOMAIN_NAME=Default
      - OS_PROJECT_NAME=admin
      - OS_USERNAME=admin
      - OS_PASSWORD=smartme
      - OS_AUTH_URL=https://demo-controller.smartme.io:5000/v3
      - OS_IDENTITY_API_VERSION=3
      - OS_IMAGE_API_VERSION=2
      - HOST="demo-controller.smartme.io"
      - ADMIN_PASS="smartme"
      - IOTRONIC_PASS="smartme"
    hostname: conductor
    volumes:
     - s4t_iotronic_conductor_config:/etc/iotronic/
     - /var/log/iotronic-conductor:/var/log/iotronic
    depends_on:
      - rabbitmq
      - keystone
      - mariadb
    command: /bin/bash -c 'iotronic-dbsync && startConductor'
    ports:
      - '8813:8812'
    networks:
      - 'default'

  ui:
    container_name: s4t_iotronic_ui
    restart: unless-stopped
    image: smartmeio/s4t_iotronic_ui:latest
    depends_on:
      - conductor
    ports:
      - '8086:80'
    networks:
      - 'default'

volumes:
  s4t_iotronic_db_data:
    name: s4t_iotronic_db_data
  s4t_iotronic_db_config:
    name: s4t_iotronic_db_config
  s4t_keystone_config:
    name: s4t_keystone_config
  s4t_keystone_data:
    name: s4t_keystone_data
  s4t_iotronic_conductor_config:
    name: s4t_iotronic_conductor_config


networks:
  default:
    name: s4t-controller-network
    driver: 'bridge'
